# algorithm_data.py
# DevSwarm 全量算法认知图谱基建数据 (基于 Luogu 体系提取)

ALGORITHM_DATA = {
    "nodes": [
        # ================= Level 0: 语言基础与基本思想 =================
        {"id": "循环与分支", "category": "基础与排序", "level": 0},
        {"id": "数组", "category": "线性数据结构", "level": 0},
        {"id": "函数与递归", "category": "基础与排序", "level": 0},
        {"id": "模拟", "category": "基础与排序", "level": 0},
        {"id": "枚举", "category": "基础与排序", "level": 0},
        {"id": "时间复杂度分析", "category": "基础与排序", "level": 0},
        {"id": "位运算", "category": "数学与数论", "level": 0},

        # ================= Level 1: 基础算法与线性数据结构 =================
        {"id": "排序算法", "category": "基础与排序", "level": 1},
        {"id": "双指针", "category": "基础与排序", "level": 1},
        {"id": "二分", "category": "基础与排序", "level": 1},
        {"id": "贪心", "category": "基础与排序", "level": 1},
        {"id": "递推", "category": "基础与排序", "level": 1},
        {"id": "高精度", "category": "高级技巧", "level": 1},
        {"id": "前缀和", "category": "线性数据结构", "level": 1},
        {"id": "差分", "category": "线性数据结构", "level": 1},
        {"id": "栈", "category": "线性数据结构", "level": 1},
        {"id": "队列", "category": "线性数据结构", "level": 1},
        {"id": "链表", "category": "线性数据结构", "level": 1},
        {"id": "字符串基础", "category": "字符串", "level": 1},
        {"id": "最大公约数 (GCD)", "category": "数学与数论", "level": 1},
        {"id": "素数判断与筛法", "category": "数学与数论", "level": 1},

        # ================= Level 2: 进阶结构与搜索策略 =================
        {"id": "单调栈", "category": "线性数据结构", "level": 2},
        {"id": "单调队列", "category": "线性数据结构", "level": 2},
        {"id": "哈希表", "category": "线性数据结构", "level": 2},
        {"id": "分治", "category": "基础与排序", "level": 2},
        {"id": "倍增", "category": "高级技巧", "level": 2},
        {"id": "二分答案", "category": "基础与排序", "level": 2},
        {"id": "三分", "category": "基础与排序", "level": 2},
        {"id": "离散化", "category": "高级技巧", "level": 2},
        {"id": "广度优先搜索 (BFS)", "category": "搜索与遍历", "level": 2},
        {"id": "深度优先搜索 (DFS)", "category": "搜索与遍历", "level": 2},
        {"id": "回溯算法", "category": "搜索与遍历", "level": 2},
        {"id": "记忆化搜索", "category": "搜索与遍历", "level": 2},
        {"id": "二叉树基础", "category": "树形数据结构", "level": 2},
        {"id": "图基础", "category": "图论", "level": 2},
        {"id": "堆 (优先队列)", "category": "树形数据结构", "level": 2},
        {"id": "并查集", "category": "树形数据结构", "level": 2},
        {"id": "字符串哈希", "category": "字符串", "level": 2},
        {"id": "快速幂", "category": "数学与数论", "level": 2},
        {"id": "排列组合", "category": "数学与数论", "level": 2},

        # ================= Level 3: 核心图论、DP与树结构 =================
        {"id": "树的遍历", "category": "树形数据结构", "level": 3},
        {"id": "图遍历", "category": "图论", "level": 3},
        {"id": "拓扑排序", "category": "图论", "level": 3},
        {"id": "最短路", "category": "图论", "level": 3},
        {"id": "生成树", "category": "图论", "level": 3},
        {"id": "字典树 (Trie)", "category": "字符串", "level": 3},
        {"id": "KMP算法", "category": "字符串", "level": 3},
        {"id": "树状数组", "category": "树形数据结构", "level": 3},
        {"id": "线段树", "category": "树形数据结构", "level": 3},
        {"id": "ST表", "category": "线性数据结构", "level": 3},
        {"id": "二叉搜索树 (BST)", "category": "树形数据结构", "level": 3},
        {"id": "线性 DP", "category": "动态规划", "level": 3},
        {"id": "背包 DP", "category": "动态规划", "level": 3},
        {"id": "区间 DP", "category": "动态规划", "level": 3},
        {"id": "扩展欧几里得算法", "category": "数学与数论", "level": 3},
        {"id": "乘法逆元", "category": "数学与数论", "level": 3},
        {"id": "容斥原理", "category": "数学与数论", "level": 3},
        {"id": "矩阵运算", "category": "数学与数论", "level": 3},

        # ================= Level 4: 高阶树/图、字符串与DP优化 =================
        {"id": "最近公共祖先 (LCA)", "category": "树形数据结构", "level": 4},
        {"id": "树的直径与重心", "category": "树形数据结构", "level": 4},
        {"id": "强连通分量", "category": "图论", "level": 4},
        {"id": "双连通分量", "category": "图论", "level": 4},
        {"id": "二分图", "category": "图论", "level": 4},
        {"id": "差分约束", "category": "图论", "level": 4},
        {"id": "AC自动机", "category": "字符串", "level": 4},
        {"id": "Manacher 算法", "category": "字符串", "level": 4},
        {"id": "Z函数 (扩展KMP)", "category": "字符串", "level": 4},
        {"id": "平衡树", "category": "树形数据结构", "level": 4},
        {"id": "可持久化数据结构", "category": "树形数据结构", "level": 4},
        {"id": "分块", "category": "高级技巧", "level": 4},
        {"id": "莫队", "category": "高级技巧", "level": 4},
        {"id": "树形 DP", "category": "动态规划", "level": 4},
        {"id": "状压 DP", "category": "动态规划", "level": 4},
        {"id": "数位 DP", "category": "动态规划", "level": 4},
        {"id": "期望 DP", "category": "动态规划", "level": 4},
        {"id": "单调队列优化 DP", "category": "动态规划", "level": 4},
        {"id": "矩阵加速", "category": "动态规划", "level": 4},
        {"id": "中国剩余定理 CRT", "category": "数学与数论", "level": 4},
        {"id": "博弈论", "category": "数学与数论", "level": 4},
        {"id": "启发式搜索 (A*)", "category": "搜索与遍历", "level": 4},
        {"id": "IDA*", "category": "搜索与遍历", "level": 4},
        {"id": "折半搜索", "category": "搜索与遍历", "level": 4},

        # ================= Level 5: 竞赛级神仙算法 =================
        {"id": "网络流", "category": "图论", "level": 5},
        {"id": "最小割", "category": "图论", "level": 5},
        {"id": "费用流", "category": "图论", "level": 5},
        {"id": "树链剖分", "category": "树形数据结构", "level": 5},
        {"id": "动态树 LCT", "category": "树形数据结构", "level": 5},
        {"id": "点分治", "category": "树形数据结构", "level": 5},
        {"id": "树套树", "category": "树形数据结构", "level": 5},
        {"id": "后缀数组 SA", "category": "字符串", "level": 5},
        {"id": "后缀自动机 SAM", "category": "字符串", "level": 5},
        {"id": "斜率优化", "category": "动态规划", "level": 5},
        {"id": "DP 套 DP", "category": "动态规划", "level": 5},
        {"id": "快速傅里叶变换 FFT", "category": "数学与数论", "level": 5},
        {"id": "快速数论变换 NTT", "category": "数学与数论", "level": 5},
        {"id": "莫比乌斯反演", "category": "数学与数论", "level": 5},
        {"id": "CDQ分治", "category": "高级技巧", "level": 5},
        {"id": "扫描线", "category": "高级技巧", "level": 5},
        {"id": "计算几何基础", "category": "高级技巧", "level": 5}
    ],

    "edges": [
        # 基本逻辑衍生
        {"source": "循环与分支", "target": "数组"},
        {"source": "循环与分支", "target": "模拟"},
        {"source": "循环与分支", "target": "枚举"},
        {"source": "函数与递归", "target": "递推"},

        # 数组与线性结构衍生
        {"source": "数组", "target": "前缀和"},
        {"source": "前缀和", "target": "差分"},
        {"source": "数组", "target": "排序算法"},
        {"source": "数组", "target": "双指针"},
        {"source": "数组", "target": "栈"},
        {"source": "数组", "target": "队列"},
        {"source": "数组", "target": "链表"},
        {"source": "数组", "target": "二分"},

        # 基础算法进阶
        {"source": "排序算法", "target": "贪心"},
        {"source": "排序算法", "target": "离散化"},
        {"source": "二分", "target": "二分答案"},
        {"source": "二分", "target": "三分"},
        {"source": "函数与递归", "target": "分治"},
        {"source": "函数与递归", "target": "深度优先搜索 (DFS)"},
        {"source": "队列", "target": "广度优先搜索 (BFS)"},
        {"source": "栈", "target": "单调栈"},
        {"source": "队列", "target": "单调队列"},
        {"source": "数组", "target": "哈希表"},

        # 字符串体系
        {"source": "数组", "target": "字符串基础"},
        {"source": "字符串基础", "target": "字符串哈希"},
        {"source": "字符串基础", "target": "字典树 (Trie)"},
        {"source": "字符串基础", "target": "KMP算法"},
        {"source": "字典树 (Trie)", "target": "AC自动机"},
        {"source": "KMP算法", "target": "AC自动机"},
        {"source": "KMP算法", "target": "Z函数 (扩展KMP)"},
        {"source": "字符串基础", "target": "Manacher 算法"},
        {"source": "字符串基础", "target": "后缀数组 SA"},
        {"source": "AC自动机", "target": "后缀自动机 SAM"},

        # 搜索与图论体系
        {"source": "深度优先搜索 (DFS)", "target": "回溯算法"},
        {"source": "深度优先搜索 (DFS)", "target": "记忆化搜索"},
        {"source": "数组", "target": "图基础"},
        {"source": "图基础", "target": "图遍历"},
        {"source": "广度优先搜索 (BFS)", "target": "图遍历"},
        {"source": "深度优先搜索 (DFS)", "target": "图遍历"},
        {"source": "图遍历", "target": "拓扑排序"},
        {"source": "图遍历", "target": "最短路"},
        {"source": "图遍历", "target": "生成树"},
        {"source": "图遍历", "target": "强连通分量"},
        {"source": "图遍历", "target": "双连通分量"},
        {"source": "最短路", "target": "差分约束"},
        {"source": "图基础", "target": "二分图"},
        {"source": "广度优先搜索 (BFS)", "target": "网络流"},
        {"source": "网络流", "target": "最小割"},
        {"source": "网络流", "target": "费用流"},
        {"source": "广度优先搜索 (BFS)", "target": "启发式搜索 (A*)"},
        {"source": "深度优先搜索 (DFS)", "target": "IDA*"},
        {"source": "深度优先搜索 (DFS)", "target": "折半搜索"},

        # 树形结构体系
        {"source": "递归", "target": "二叉树基础"},
        {"source": "二叉树基础", "target": "树的遍历"},
        {"source": "二叉树基础", "target": "堆 (优先队列)"},
        {"source": "二叉树基础", "target": "二叉搜索树 (BST)"},
        {"source": "二叉搜索树 (BST)", "target": "平衡树"},
        {"source": "堆 (优先队列)", "target": "最短路"},
        {"source": "树的遍历", "target": "最近公共祖先 (LCA)"},
        {"source": "树的遍历", "target": "树的直径与重心"},
        {"source": "树的遍历", "target": "树链剖分"},
        {"source": "树的遍历", "target": "点分治"},
        {"source": "平衡树", "target": "动态树 LCT"},

        # 数据结构体系
        {"source": "前缀和", "target": "树状数组"},
        {"source": "位运算", "target": "树状数组"},
        {"source": "分治", "target": "线段树"},
        {"source": "倍增", "target": "ST表"},
        {"source": "最近公共祖先 (LCA)", "target": "ST表"},
        {"source": "线段树", "target": "可持久化数据结构"},
        {"source": "线段树", "target": "树套树"},
        {"source": "线段树", "target": "扫描线"},
        {"source": "双指针", "target": "莫队"},
        {"source": "分块", "target": "莫队"},

        # 动态规划 (DP) 体系
        {"source": "递推", "target": "线性 DP"},
        {"source": "记忆化搜索", "target": "线性 DP"},
        {"source": "线性 DP", "target": "背包 DP"},
        {"source": "线性 DP", "target": "区间 DP"},
        {"source": "线性 DP", "target": "树形 DP"},
        {"source": "树的遍历", "target": "树形 DP"},
        {"source": "位运算", "target": "状压 DP"},
        {"source": "线性 DP", "target": "状压 DP"},
        {"source": "线性 DP", "target": "数位 DP"},
        {"source": "排列组合", "target": "期望 DP"},
        {"source": "单调队列", "target": "单调队列优化 DP"},
        {"source": "矩阵运算", "target": "矩阵加速"},
        {"source": "计算几何基础", "target": "斜率优化"},
        {"source": "线性 DP", "target": "DP 套 DP"},

        # 数学与数论体系
        {"source": "时间复杂度分析", "target": "最大公约数 (GCD)"},
        {"source": "最大公约数 (GCD)", "target": "素数判断与筛法"},
        {"source": "最大公约数 (GCD)", "target": "扩展欧几里得算法"},
        {"source": "扩展欧几里得算法", "target": "乘法逆元"},
        {"source": "乘法逆元", "target": "排列组合"},
        {"source": "乘法逆元", "target": "组合数学"},
        {"source": "乘法逆元", "target": "中国剩余定理 CRT"},
        {"source": "递归", "target": "快速幂"},
        {"source": "排列组合", "target": "容斥原理"},
        {"source": "素数判断与筛法", "target": "莫比乌斯反演"},
        {"source": "矩阵运算", "target": "快速傅里叶变换 FFT"},
        {"source": "快速傅里叶变换 FFT", "target": "快速数论变换 NTT"},

        # 其他高级技巧
        {"source": "分治", "target": "CDQ分治"},
        {"source": "并查集", "target": "生成树"}
    ]
}